# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('price', models.IntegerField()),
                ('gift_img', models.CharField(max_length=500)),
                ('gift_rank', models.IntegerField(default=0)),
                ('uploading_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('Parent', 'Parent'), ('Grandparent', 'Grandparent'), ('Sibling', 'Sibling'), ('Cousin', 'Cousin'), ('Parent in law', 'Parent in law'), ('Nephew', 'Nephew'), ('Friend', 'Friend'), ('Partner', 'Partner'), ('Child', 'Child'), ('Child in law', 'Child in law'), ('Grandparent in law', 'Grandparent in law'), ('Uncle/Aunt', 'Uncle/Aunt'), ('Sibling in law', 'Sibling in law'), ('Acquaintant', 'Acquaintant'), ('Colleague', 'Colleague'), ('Grandson', 'Grandson')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipMatrixCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField()),
                ('rel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel1', to='gifted.Relation')),
                ('rel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel2', to='gifted.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user_rank', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifted.Relation'),
        ),
        migrations.AddField(
            model_name='gift',
            name='uploading_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifted.User'),
        ),
    ]
