# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('price', models.IntegerField()),
                ('gift_img', models.CharField(max_length=500)),
                ('gift_rank', models.IntegerField(default=0)),
                ('uploading_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('description', models.CharField(choices=[('parent', 'Parent'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('cousin', 'Cousin'), ('parent_in_law', 'Parent in law'), ('nephew', 'Nephew'), ('friend', 'Friend'), ('partner', 'Partner'), ('child', 'Child'), ('child_in_law', 'Child in law'), ('grandparent_in_law', 'Grandparent in law'), ('uncle_aunt', 'Uncle/Aunt'), ('sibling_in_law', 'Sibling in law'), ('acquaintant', 'Acquaintant'), ('colleague', 'Colleague'), ('grandson', 'Grandson')], max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipMatrixCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField()),
                ('rel1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel1', to='gifted.Relation')),
                ('rel2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel2', to='gifted.Relation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('user_rank', models.IntegerField(default=0)),
                ('gifts_removed', models.IntegerField(default=0)),
                ('is_banned', models.BooleanField(default=False)),
                ('banned_start', models.DateTimeField(blank=True, null=True)),
                ('liked_gift_ids', models.TextField(default='[]')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifted.Relation'),
        ),
        migrations.AddField(
            model_name='gift',
            name='uploading_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifted.User'),
        ),
    ]
