# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifted', '0002_auto_20170512_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='gift_img',
            field=models.CharField(max_length=500),
        ),
    ]
